const { test, expect, describe } = require('@playwright/test');
const urls = require('../../../config/url');
const pages = [
  {
    label: 'Default',
    key: 'base',
    expectedH1: 'India’s fastest growing commercial vehicle website',
    expectedH2: [
      'Select Brand',
      'What are you looking for?',
      'Most Popular Commercial Trucks',
      'Search Commercial Truck By Brands',  
      'Most Popular Commercial Buses',
      'Search Commercial Bus By Brands',
      'Most Popular Commercial Auto Rickshaw',
      'Search Commercial Auto Rickshaw By Brands',
      'Most Popular Commercial Auto Rickshaw',          
      'Search Commercial Auto Rickshaw By Brands',
      'Most Popular Comparison',
      'Latest News',
    ],
    expectedH3: [
     "Pick Up Trucks",
    "Buses",
    "Mini Trucks",
    "Trucks",
    "Three Wheelers",
    "Ashok Leyland",
    "Bada Dost i4",
    "Mahindra",
    "Bolero Maxx Pickup City",
    "Tata",
    "Intra V30",
    "Tata",
    "Ace Gold Petrol",
    "Tata",
    "Intra V70",
    "Mahindra",
    "Veero CNG",
    "Ashok Leyland",
    "Ecomet 1015 Tipper",
    "Swaraj Mazda",
    "Samrat GS",
    "Eicher",
    "Pro 2110",
    "Tata",
    "Ace EV",
    "Tata",
    "Intra V30",
    "Tata",
    "Ace Gold Petrol",
    "Tata",
    "Ace EV",
    "Mahindra",
    "Bolero Pikup ExtraLong",
    "Tata",
    "Ace Gold CNG",
    "Tata",
    "Ace Gold Diesel Plus",
    "Tata",
    "Ace Gold CNG Plus",
    "Tata",
    "Ace Gold Petrol CX",
    "Tata",
    "Ace EV 1000",
    "Tata",
    "Winger Cargo",
    "Tata",
    "Ace EV",
    "Mahindra",
    "Zeo",
    "Montra",
    "Eviator",
    "Tata",
    "Ace Pro EV",
    "Tata",
    "Prima E.28K",
    "Tata",
    "Ace EV 1000",
    "Eicher",
    "Pro 2055 EV",
    "Omega Seiki Mobility",
    "M1KA 1.0",
    "Eicher",
    "Pro 8035XM",
    "Eicher",
    "Pro 2049 EV",
    "Ashok Leyland",
    "Ecomet 1015 Tipper",
    "Tata",
    "Signa 2823.K HD 9S",
    "Tata",
    "Signa 2823.K RMC STD 6S",
    "Tata",
    "Signa 2823.K/.TK 6S STD",
    "Tata",
    "Signa 2825.K/.TK",
    "Tata",
    "Signa 4225.TK",
    "Tata",
    "Signa 4825 TK",
    "Tata",
    "610 SK",
    "Tata",
    "912 LPK",
    "Tata",
    "Prima 2825.K/.TK",
    "Force",
    "Traveller 26",
    "Tata",
    "Starbus City",
    "Volvo",
    "9400 B11R",
    "Tata",
    "Ultra Ev 9",
    "EKA",
    "9M",
    "Tata",
    "Magna Coach",
    "Swaraj Mazda",
    "S7 School Bus",
    "Tata",
    "Magic Express M2",
    "Tata",
    "Intercity EV 2.0",
    "Tata",
    "LP 909 Starbus",
    "Tata",
    "Ultra Ev 9",
    "EKA",
    "9M",
    "Tata",
    "Intercity EV 2.0",
    "Tata",
    "Starbus EV 4 12 Low Entry Electric Bus",
    "SML Isuzu",
    "Hiroi.ev",
    "Mahindra",
    "E-Supro Van",
    "Mahindra",
    "E-Supro Cargo Van",
    "Switch",
    "EiV 12",
    "Tata",
    "Starbus Urban City Electric",
    "Switch",
    "MetroDecker",
    "Tata",
    "Starbus School LP 810",
    "Tata",
    "Starbus Staff Contract",
    "Tata",
    "Starbus Ultra Staff Contract",
    "Tata",
    "Starbus Ultra School",
    "Tata",
    "City Ride Skool",
    "Tata",
    "LP 407 Starbus Skool CNG",
    "Tata",
    "LP 912 Starbus Skool AC",
    "Tata",
    "LP 410 Starbus Skool",
    "Tata",
    "LP 913 Starbus Skool CNG AC",
    "Tata",
    "LP 909 Starbus Skool CNG",
    "Tata",
    "Starbus Ultra Sub Urban",
    "Tata",
    "Starbus Sub Urban",
    "Ashok Leyland",
    "Cheetah",
    "Scania",
    "Touring Bus HD",
    "Scania",
    "Citywide",
    "Scania",
    "Interlink",
    "Scania",
    "Higer A30",
    "Ashok Leyland",
    "Oyster Tourist Bus",
    "Ashok Leyland",
    "Oyster Wide Tourist Bus",
    "Ashok Leyland",
    "Viking Tourist Bus",
    "Montra",
    "Super Auto",
    "Omega Seiki Mobility",
    "Stream City Qik",
    "Omega Seiki Mobility",
    "Stream City",
    "Bajaj",
    "GoGo",
    "Bajaj",
    "RE CNG",
    "Mahindra",
    "E-Alfa Mini",
    "Mahindra",
    "Alfa Plus",
    "Mahindra",
    "Alfa DX CNG",
    "Piaggio",
    "Ape Xtra LDX",
    "Piaggio",
    "Ape Auto DX",
    "Montra",
    "Super Auto",
    "Omega Seiki Mobility",
    "Stream City Qik",
    "Omega Seiki Mobility",
    "Stream City",
    "Bajaj",
    "GoGo",
    "Mahindra",
    "E-Alfa Mini",
    "Bajaj",
    "Maxima XL",
    "Mahindra",
    "E-Alfa Super",
    "Mahindra",
    "E-Alfa Plus",
    "Euler Motors",
    "HiCity",
    "Mahindra",
    "Treo Yaari",
    "Bajaj",
    "RE CNG",
    "Mahindra",
    "Alfa DX CNG",
    "Piaggio",
    "Ape Xtra LDX",
    "Piaggio",
    "Ape Auto DX",
    "TVS",
    "King Duramax Plus",
    "Mahindra",
    "Alfa Load",
    "ATUL",
    "GEM Cargo",
    "ATUL",
    "Gem Paxx",
    "ATUL",
    "Rik",
    "ATUL",
    "Smart Cargo",
    "Ashok Leyland",
    "Bada Dost i3",
    "Mahindra",
    "Bolero Pikup ExtraLong",
    "Mahindra",
    "Bolero Pikup ExtraLong",
    "Tata",
    "407 Gold 29WB",
    "Mahindra",
    "Bolero Maxx Pickup HD",
    "Tata",
    "Intra V70",
    "Ashok Leyland",
    "Bada Dost i4",
    "Mahindra",
    "Bolero Pikup 4WD",
    "Ashok Leyland",
    "Bada Dost i4",
    "Mahindra",
    //"Bolero Pikup CNG",
    "Mahindra",
    "Bolero Pikup 1.7T",
    "Tata",
    "Intra V70",
    "About 91trucks",
    "Work with us",
    "Useful Links",
    "Our Partner Website",
    "Get Connected"
    ],
    expectedH4: [
      "About Us", "Contact Us", "Privacy Policy", "Terms and Conditions", "Advertise With Us", "Feedback", "Career", "Trucks", "Buses", "Auto Rickshaws"
    ]
  },
  {
    label: 'English',
    key: 'english',
    expectedH1: 'India’s fastest growing commercial vehicle website',
    expectedH2: [
      'Select Brand',
      'What are you looking for?',
      'Most Popular Commercial Trucks',
      'Search Commercial Truck By Brands',  
      'Most Popular Commercial Buses',
      'Search Commercial Bus By Brands',
      'Most Popular Commercial Auto Rickshaw',
      'Search Commercial Auto Rickshaw By Brands',
      'Most Popular Commercial Auto Rickshaw',          
      'Search Commercial Auto Rickshaw By Brands',
      'Most Popular Comparison',
      'Latest News',
    ],
    expectedH3: [
      "Pick Up Trucks",
    "Buses",
    "Mini Trucks",
    "Trucks",
    "Three Wheelers",
    "Ashok Leyland",
    "Bada Dost i4",
    "Mahindra",
    "Bolero Maxx Pickup City",
    "Tata",
    "Intra V30",
    "Tata",
    "Ace Gold Petrol",
    "Tata",
    "Intra V70",
    "Mahindra",
    "Veero CNG",
    "Ashok Leyland",
    "Ecomet 1015 Tipper",
    "Swaraj Mazda",
    "Samrat GS",
    "Eicher",
    "Pro 2110",
    "Tata",
    "Ace EV",
    "Tata",
    "Intra V30",
    "Tata",
    "Ace Gold Petrol",
    "Tata",
    "Ace EV",
    "Mahindra",
    "Bolero Pikup ExtraLong",
    "Tata",
    "Ace Gold CNG",
    "Tata",
    "Ace Gold Diesel Plus",
    "Tata",
    "Ace Gold CNG Plus",
    "Tata",
    "Ace Gold Petrol CX",
    "Tata",
    "Ace EV 1000",
    "Tata",
    "Winger Cargo",
    "Tata",
    "Ace EV",
    "Mahindra",
    "Zeo",
    "Montra",
    "Eviator",
    "Tata",
    "Ace Pro EV",
    "Tata",
    "Prima E.28K",
    "Tata",
    "Ace EV 1000",
    "Eicher",
    "Pro 2055 EV",
    "Omega Seiki Mobility",
    "M1KA 1.0",
    "Eicher",
    "Pro 8035XM",
    "Eicher",
    "Pro 2049 EV",
    "Ashok Leyland",
    "Ecomet 1015 Tipper",
    "Tata",
    "Signa 2823.K HD 9S",
    "Tata",
    "Signa 2823.K RMC STD 6S",
    "Tata",
    "Signa 2823.K/.TK 6S STD",
    "Tata",
    "Signa 2825.K/.TK",
    "Tata",
    "Signa 4225.TK",
    "Tata",
    "Signa 4825 TK",
    "Tata",
    "610 SK",
    "Tata",
    "912 LPK",
    "Tata",
    "Prima 2825.K/.TK",
    "Force",
    "Traveller 26",
    "Tata",
    "Starbus City",
    "Volvo",
    "9400 B11R",
    "Tata",
    "Ultra Ev 9",
    "EKA",
    "9M",
    "Tata",
    "Magna Coach",
    "Swaraj Mazda",
    "S7 School Bus",
    "Tata",
    "Magic Express M2",
    "Tata",
    "Intercity EV 2.0",
    "Tata",
    "LP 909 Starbus",
    "Tata",
    "Ultra Ev 9",
    "EKA",
    "9M",
    "Tata",
    "Intercity EV 2.0",
    "Tata",
    "Starbus EV 4 12 Low Entry Electric Bus",
    "SML Isuzu",
    "Hiroi.ev",
    "Mahindra",
    "E-Supro Van",
    "Mahindra",
    "E-Supro Cargo Van",
    "Switch",
    "EiV 12",
    "Tata",
    "Starbus Urban City Electric",
    "Switch",
    "MetroDecker",
    "Tata",
    "Starbus School LP 810",
    "Tata",
    "Starbus Staff Contract",
    "Tata",
    "Starbus Ultra Staff Contract",
    "Tata",
    "Starbus Ultra School",
    "Tata",
    "City Ride Skool",
    "Tata",
    "LP 407 Starbus Skool CNG",
    "Tata",
    "LP 912 Starbus Skool AC",
    "Tata",
    "LP 410 Starbus Skool",
    "Tata",
    "LP 913 Starbus Skool CNG AC",
    "Tata",
    "LP 909 Starbus Skool CNG",
    "Tata",
    "Starbus Ultra Sub Urban",
    "Tata",
    "Starbus Sub Urban",
    "Ashok Leyland",
    "Cheetah",
    "Scania",
    "Touring Bus HD",
    "Scania",
    "Citywide",
    "Scania",
    "Interlink",
    "Scania",
    "Higer A30",
    "Ashok Leyland",
    "Oyster Tourist Bus",
    "Ashok Leyland",
    "Oyster Wide Tourist Bus",
    "Ashok Leyland",
    "Viking Tourist Bus",
    "Montra",
    "Super Auto",
    "Omega Seiki Mobility",
    "Stream City Qik",
    "Omega Seiki Mobility",
    "Stream City",
    "Bajaj",
    "GoGo",
    "Bajaj",
    "RE CNG",
    "Mahindra",
    "E-Alfa Mini",
    "Mahindra",
    "Alfa Plus",
    "Mahindra",
    "Alfa DX CNG",
    "Piaggio",
    "Ape Xtra LDX",
    "Piaggio",
    "Ape Auto DX",
    "Montra",
    "Super Auto",
    "Omega Seiki Mobility",
    "Stream City Qik",
    "Omega Seiki Mobility",
    "Stream City",
    "Bajaj",
    "GoGo",
    "Mahindra",
    "E-Alfa Mini",
    "Bajaj",
    "Maxima XL",
    "Mahindra",
    "E-Alfa Super",
    "Mahindra",
    "E-Alfa Plus",
    "Euler Motors",
    "HiCity",
    "Mahindra",
    "Treo Yaari",
    "Bajaj",
    "RE CNG",
    "Mahindra",
    "Alfa DX CNG",
    "Piaggio",
    "Ape Xtra LDX",
    "Piaggio",
    "Ape Auto DX",
    "TVS",
    "King Duramax Plus",
    "Mahindra",
    "Alfa Load",
    "ATUL",
    "GEM Cargo",
    "ATUL",
    "Gem Paxx",
    "ATUL",
    "Rik",
    "ATUL",
    "Smart Cargo",
    "Ashok Leyland",
    "Bada Dost i3",
    "Mahindra",
    "Bolero Pikup ExtraLong",
    "Mahindra",
    "Bolero Pikup ExtraLong",
    "Tata",
    "407 Gold 29WB",
    "Mahindra",
    "Bolero Maxx Pickup HD",
    "Tata",
    "Intra V70",
    "Ashok Leyland",
    "Bada Dost i4",
    "Mahindra",
    "Bolero Pikup 4WD",
    "Ashok Leyland",
    "Bada Dost i4",
    "Mahindra",
    //"Bolero Pikup CNG",
    "Mahindra",
    "Bolero Pikup 1.7T",
    "Tata",
    "Intra V70",
    "About 91trucks",
    "Work with us",
    "Useful Links",
    "Our Partner Website",
    "Get Connected"
    ],
    expectedH4: [
      "About Us", "Contact Us", "Privacy Policy", "Terms and Conditions", "Advertise With Us", "Feedback", "Career", "Trucks", "Buses", "Auto Rickshaws"
    ]
  },
  {
    label: 'Hindi',
    key: 'hindi',
    expectedH1: 'भारत की सबसे तेज़ी से बढ़ती कमर्शियल वाहनों की वेबसाइट',
    expectedH2: [
      "ब्रांड चुनें", "आप क्या ढूंढ रहे है", "लोकप्रिय ट्रक", "ब्रांड के आधार पर ट्रक खोजें", "लोकप्रिय बस", "ब्रांड के आधार पर बस खोजें", "लोकप्रिय ऑटो रिक्शा", "ब्रांड के आधार पर ऑटो रिक्शा खोजें", "सर्वाधिक लोकप्रिय तुलनाएँ", "लेटेस्ट न्यूज़"
    ],
    expectedH3: [
      "पिकअप ट्रक",
    "बस",
    "मिनी ट्रक",
    "ट्रक",
    "थ्री व्हीलर",
    "अशोक लेलैंड",
    "बड़ा दोस्त i4",
    "महिंद्रा",
    "बोलेरो मैक्सी पिकअप सिटी",
    "टाटा",
    "इंट्रा वी30",
    "टाटा",
    "एस गोल्ड पेट्रोल",
    "टाटा",
    "Intra V70",
    "अशोक लेलैंड",
    "इकोमेट 1015 टिपर",
    "स्वराज माजदा",
    "सम्राट जीएस",
    "आइशर",
    "प्रो 2110",
    "टाटा",
    "ऐस ईवी",
    "महिंद्रा",
    "वीरो",
    "टाटा",
    "इंट्रा वी30",
    "टाटा",
    "एस गोल्ड पेट्रोल",
    "टाटा",
    "ऐस ईवी",
    "महिंद्रा",
    "बोलेरो पिकअप एक्स्ट्रा लॉन्ग",
    "टाटा",
    "एस गोल्ड सीएनजी",
    "टाटा",
    "एस गोल्ड डीजल प्लस",
    "टाटा",
    "एस गोल्ड सीएनजी प्लस",
    "टाटा",
    "एस गोल्ड पेट्रोल सीएक्स",
    "टाटा",
    "विंगर कार्गो",
    "टाटा",
    "Ace EV 1000",
    "टाटा",
    "ऐस ईवी",
    "महिंद्रा",
    "ज़ीओ",
    "मोंट्रा",
    "Eviator",
    "टाटा",
    "Ace Pro EV",
    "टाटा",
    "प्राइमा ई.28के",
    "टाटा",
    "Ace EV 1000",
    "आइशर",
    "Pro 2055 EV",
    "ओमेगा सेइकी मोबिलिटी",
    "M1KA 1.0",
    "आइशर",
    "प्रो 8035एक्स एम",
    "आइशर",
    "प्रो 2049 ईवी",
    "अशोक लेलैंड",
    "इकोमेट 1015 टिपर",
    "टाटा",
    "प्राइमा 2825.के/टीके",
    "टाटा",
    "प्राइमा 2830.के",
    "टाटा",
    "प्राइमा 3525.के/टीके",
    "टाटा",
    "प्राइमा 3530.के",
    "टाटा",
    "सिग्ना 1923.के",
    "टाटा",
    "610 एस के",
    "टाटा",
    "912 एल पी के",
    "टाटा",
    "सिग्ना 2823.के ड्रिल रिग",
    "टाटा",
    "सिग्ना 4825.टीके",
    "फोर्स",
    "ट्रैवेलर 26",
    "वोल्वो",
    "9400 बी11आर",
    "टाटा",
    "स्टारबस सिटी",
    "टाटा",
    "Ultra Ev 9",
    "इका",
    "9M",
    "टाटा",
    "Magna Coach",
    "टाटा",
    "मैजिक एक्सप्रेस एम2",
    "स्वराज माजदा",
    "एस",
    "टाटा",
    "Intercity EV 2.0",
    "टाटा",
    "मैजिक एक्सप्रेस एम्बुलेंस",
    "टाटा",
    "Ultra Ev 9",
    "इका",
    "9M",
    "टाटा",
    "Intercity EV 2.0",
    "टाटा",
    "स्टारबस ईवी 4 12 लो एंट्री इलेक्ट्रिक बस",
    "एसएमएल इसुजु",
    "Hiroi.ev",
    "महिंद्रा",
    "ई-सुप्रो वैन",
    "महिंद्रा",
    "ई-सुप्रो कार्गो वैन",
    "स्विच",
    "ईवी 12",
    "टाटा",
    "स्टारबस अर्बन सिटी इलेक्ट्रिक",
    "टाटा",
    "स्टारबस ईवी 4 12 लो फ्लोर इलेक्ट्रिक",
    "टाटा",
    "स्टारबस स्कूल एलपी 810",
    "टाटा",
    "स्टारबस स्टाफ कॉन्ट्रैक्ट",
    "टाटा",
    "एलपी 912 स्टारबस स्कूल एसी",
    "टाटा",
    "एलपी 407 स्टारबस स्कूल सीएनजी",
    "टाटा",
    "स्टारबस उल्ट्रा स्टाफ कॉन्ट्रैक्ट",
    "टाटा",
    "स्टारबस उल्ट्रा स्कूल",
    "टाटा",
    "सिटी राइड स्कूल",
    "टाटा",
    "एलपी 913 स्टारबस स्कूल सीएनजी एसी",
    "टाटा",
    "एलपी 410 स्टारबस स्कूल",
    "टाटा",
    "एलपी 909 स्टारबस स्कूल सीएनजी",
    "टाटा",
    "स्टारबस सब उर्बन",
    "टाटा",
    "स्टारबस उल्ट्रा सब उर्बन",
    "अशोक लेलैंड",
    "चीता",
    "स्कैनिया",
    "टूरिंग बस एच डी",
    "स्कैनिया",
    "सिटीवाइड",
    "अशोक लेलैंड",
    "ऑइस्टर टूरिस्ट बस",
    "अशोक लेलैंड",
    "ऑइस्टर वाइड टूरिस्ट बस",
    "अशोक लेलैंड",
    "वाइकिंग टूरिस्ट बस",
    "अशोक लेलैंड",
    "12एम एफ ई इंटरसिटी",
    "स्कैनिया",
    "इंटरलिंक",
    "मोंट्रा",
    "सुपर ऑटो",
    "ओमेगा सेइकी मोबिलिटी",
    "Stream City Qik",
    "ओमेगा सेइकी मोबिलिटी",
    "Stream City",
    "बजाज",
    "GoGo",
    "बजाज",
    "आरई सीएनजी",
    "पियाजियो",
    "एपे एक्सट्रा एलडीएक्स",
    "पियाजियो",
    "एपे ऑटो डीएक्स",
    "महिंद्रा",
    "ई-अल्फा मिनी",
    "महिंद्रा",
    "अल्फा प्लस",
    "महिंद्रा",
    "अल्फा डीएक्स सीएनजी",
    "मोंट्रा",
    "सुपर ऑटो",
    "ओमेगा सेइकी मोबिलिटी",
    "Stream City Qik",
    "ओमेगा सेइकी मोबिलिटी",
    "Stream City",
    "बजाज",
    "GoGo",
    "महिंद्रा",
    "ई-अल्फा मिनी",
    "बजाज",
    "मैक्सिमा एक्सएल",
    "महिंद्रा",
    "ई-अल्फा सुपर",
    "महिंद्रा",
    "E-Alfa Plus",
    "यूलर मोटर्स",
    "HiCity",
    "महिंद्रा",
    "त्रियो यारी",
    "बजाज",
    "आरई सीएनजी",
    "पियाजियो",
    "एपे एक्सट्रा एलडीएक्स",
    "पियाजियो",
    "एपे ऑटो डीएक्स",
    "महिंद्रा",
    "अल्फा डीएक्स सीएनजी",
    "टीवीएस",
    "King Duramax Plus",
    "महिंद्रा",
    "अल्फा लोड",
    "अटुल",
    "जेएम कार्गो",
    "अटुल",
    "जेएम पैक्स",
    "अटुल",
    "रिक",
    "अटुल",
    "स्मार्ट कार्गो",
    "अशोक लेलैंड",
    "बड़ा दोस्त i3",
    "महिंद्रा",
    "बोलेरो पिकअप एक्स्ट्रा लॉन्ग",
    "महिंद्रा",
    "बोलेरो पिकअप एक्स्ट्रा लॉन्ग",
    "टाटा",
    "407 गोल्ड 29डब्ल्यूबी",
    "महिंद्रा",
    "बोलेरो मैक्सी पिकअप एच डी",
    "टाटा",
    "Intra V70",
    "अशोक लेलैंड",
    "बड़ा दोस्त i4",
    "महिंद्रा",
    "बोलेरो पिकअप 4डब्ल्यू डी",
    "अशोक लेलैंड",
    "बड़ा दोस्त i4",
    "महिंद्रा",
    //"बोलेरो पिकअप सीएनजी",
    "महिंद्रा",
    "बोलेरो पिकअप 1.7टी",
    "टाटा",
    "Intra V70",
    "91trucks  के बारे में",
    "हमारे साथ काम करें",
    "उपयोगी लिंक",
    "हमारी साझेदार वेबसाइट",
    "हम से जुड़ें"
    ],
    expectedH4: [
      'हमारे बारे में',
      'संपर्क करें',
      'गोपनीयता नीति',
      'नियम और शर्तें',
      'हमारे साथ विज्ञापन',
      'प्रतिक्रिया',
      'करियर',
      'ट्रक्स',
      'बस',
      'ऑटो',
    ]
  },
 ];


function normalizeText(text) {
  return text.replace(/\s+/g, ' ').trim();
}

pages.forEach(({  label, key, expectedH1, expectedH2, expectedH3, expectedH4 }) => {
  test.describe(`${label} Page Headings`, () => {

    test.beforeEach(async ({ page }) => {
      await page.goto(urls[key]);
    });

     test(`${label} - H1 Content Validation`, async ({ page }) => {
      await page.goto(urls[key], { waitUntil: 'networkidle' });
      const h1 = page.locator('h1', { hasText: expectedH1 });
      await expect(h1).toHaveCount(1);
      const h1Text = await h1.first().textContent();
      expect(h1Text.trim()).toBe(expectedH1);
    });

    test(`${label} - Only One H1 Tag Should Exist`, async ({ page }) => {
      await page.goto(urls[key], { waitUntil: 'domcontentloaded' });

      const h1Elements = page.locator('h1');
      const count = await h1Elements.count();
      if (count !== 1) {
        const allH1Texts = [];
        for (let i = 0; i < count; i++) {
          const text = await h1Elements.nth(i).textContent();
          allH1Texts.push(`H1[${i + 1}]: ${text.trim()}`);
        }
        console.warn(`⚠️ ${label} - Expected 1 <h1>, found ${count}:\n` + allH1Texts.join('\n'));
      }

      expect(count).toBe(1);
    });

    test(`${label} - H1 Tag Should Be Visible`, async ({ page }) => {
      await page.goto(urls[key], { waitUntil: 'domcontentloaded' });
      const h1 = page.locator('h1');
      await expect(h1.first()).toBeVisible();
    });

    test(`${label} - H1 Should Be In Viewport on Load`, async ({ page }) => {
      await page.goto(urls[key], { waitUntil: 'domcontentloaded' });

      const h1 = page.locator('h1');
      const isVisible = await h1.first().isVisible();
      const isInViewport = await h1.first().evaluate(el => {
        const rect = el.getBoundingClientRect();
        return rect.top >= 0 && rect.bottom <= window.innerHeight;
      });
      expect(isVisible).toBeTruthy();
      expect(isInViewport).toBeTruthy();
    });

    test(`${label} - H1 Should Contain Only Text`, async ({ page }) => {
      await page.goto(urls[key], { waitUntil: 'domcontentloaded' });
      const h1 = await page.locator('h1').first();
      const innerHTML = await h1.innerHTML();
      const hasNestedTags = /<\/?[a-z][\s\S]*>/i.test(innerHTML.trim());
      expect(hasNestedTags).toBeFalsy();
    });
  

    test(`should have correct h2 elements`, async ({ page }) => {
      const h2s = (await page.locator('h2').allTextContents()).map(normalizeText);
      for (const expected of expectedH2) {
        expect(h2s).toContain(normalizeText(expected));
      }
    });

    test(`should have correct h3 elements`, async ({ page }) => {
      const h3s = (await page.locator('h3').allTextContents()).map(normalizeText);

      for (const expected of expectedH3) {
    const normalizedExpected = normalizeText(expected);
    const isFound = h3s.some(h => h.includes(normalizedExpected));

    if (!isFound) {
      console.log(`❌ '${expected}' not found in:\n`, h3s);
      expect.fail(`❌ '${expected}' not found in h3 list`);
    }
}
    });

    test(`should have correct h4 elements`, async ({ page }) => {
      const h4s = (await page.locator('h4').allTextContents()).map(normalizeText);
      for (const expected of expectedH4) {
        expect(h4s).toContain(normalizeText(expected));
      }
    });

  });
});